services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: app:latest
    container_name: app
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    environment:
      - PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: on-failure:5
